class Autogenerated {
  List<Documents>? documents;
  Meta? meta;

  Autogenerated({this.documents, this.meta});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['documents'] != null) {
      documents = <Documents>[];
      json['documents'].forEach((v) {
        documents!.add(new Documents.fromJson(v));
      });
    }
    meta = json['meta'] != null ? new Meta.fromJson(json['meta']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.documents != null) {
      data['documents'] = this.documents!.map((v) => v.toJson()).toList();
    }
    if (this.meta != null) {
      data['meta'] = this.meta!.toJson();
    }
    return data;
  }
}

class Documents {
  String? contents;
  String? datetime;
  String? title;
  String? url;

  Documents({this.contents, this.datetime, this.title, this.url});
// 역직렬화 생성자 Json데이터를 받아서 Documents 객체로 만드는 역할
  Documents.fromJson(Map<String, dynamic> json) {
    contents = json['contents'];
    datetime = json['datetime'];
    title = json['title'];
    url = json['url'];
  }
// Documents 객체를 JSON 형식으로 변환(직렬화)하는 메서드
  Map<String, dynamic> toJson() { // 객체를 JSON(Map)으로 변환하는 메서드
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['contents'] = this.contents;
    data['datetime'] = this.datetime;
    data['title'] = this.title;
    data['url'] = this.url;
    return data;
  }
}

class Meta {
  bool? isEnd; // ?가 붙어 있으므로 null일 수 있는 값
  int? pageableCount;
  int? totalCount;

  Meta({this.isEnd, this.pageableCount, this.totalCount});
// Meta 클래스의 역직렬화인 fromJson() JSON데이터를 받아서 Meta객체로 바꾸는 함수
  Meta.fromJson(Map<String, dynamic> json) {
    isEnd = json['is_end'];
    pageableCount = json['pageable_count'];
    totalCount = json['total_count'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['is_end'] = this.isEnd;
    data['pageable_count'] = this.pageableCount;
    data['total_count'] = this.totalCount;
    return data;
  }
}